TURBO ON
WAIT 420
HOLD START
WAIT 4
RELEASE START
WAIT 8
WAIT 300
WRITE_RAM8 6A 87
HOLD LEFT
WAIT 40
RELEASE LEFT
HOLD UP
WAIT 40
RELEASE UP
HOLD RIGHT
WAIT 40
RELEASE RIGHT
HOLD DOWN
WAIT 40
RELEASE DOWN
HOLD LEFT
WAIT 40
RELEASE LEFT
HOLD DOWN
WAIT 40
RELEASE DOWN
HOLD RIGHT
WAIT 40
RELEASE RIGHT
HOLD UP
WAIT 40
RELEASE UP
WAIT 200
WRITE_RAM8 6A 01
HOLD LEFT
WAIT 40
RELEASE LEFT
HOLD UP
WAIT 40
RELEASE UP
HOLD RIGHT
WAIT 40
RELEASE RIGHT
HOLD DOWN
WAIT 40
RELEASE DOWN
HOLD LEFT
WAIT 40
RELEASE LEFT
HOLD DOWN
WAIT 40
RELEASE DOWN
HOLD RIGHT
WAIT 40
RELEASE RIGHT
HOLD UP
WAIT 40
RELEASE UP
HOLD LEFT
WAIT 40
RELEASE LEFT
HOLD UP
WAIT 40
RELEASE UP
HOLD RIGHT
WAIT 40
RELEASE RIGHT
HOLD DOWN
WAIT 40
RELEASE DOWN
HOLD LEFT
WAIT 40
RELEASE LEFT
HOLD DOWN
WAIT 40
RELEASE DOWN
HOLD RIGHT
WAIT 40
RELEASE RIGHT
HOLD UP
WAIT 40
RELEASE UP
WAIT 25
SCREENSHOT C:/Recomp/PacMan/PacManRecomp/tests/out/%P_i01.png
WAIT 25
SCREENSHOT C:/Recomp/PacMan/PacManRecomp/tests/out/%P_i02.png
WAIT 25
SCREENSHOT C:/Recomp/PacMan/PacManRecomp/tests/out/%P_i03.png
WAIT 25
SCREENSHOT C:/Recomp/PacMan/PacManRecomp/tests/out/%P_i04.png
WAIT 25
SCREENSHOT C:/Recomp/PacMan/PacManRecomp/tests/out/%P_i05.png
WAIT 25
SCREENSHOT C:/Recomp/PacMan/PacManRecomp/tests/out/%P_i06.png
WAIT 25
SCREENSHOT C:/Recomp/PacMan/PacManRecomp/tests/out/%P_i07.png
WAIT 25
SCREENSHOT C:/Recomp/PacMan/PacManRecomp/tests/out/%P_i08.png
WAIT 25
SCREENSHOT C:/Recomp/PacMan/PacManRecomp/tests/out/%P_i09.png
WAIT 25
SCREENSHOT C:/Recomp/PacMan/PacManRecomp/tests/out/%P_i10.png
WAIT 25
SCREENSHOT C:/Recomp/PacMan/PacManRecomp/tests/out/%P_i11.png
WAIT 25
SCREENSHOT C:/Recomp/PacMan/PacManRecomp/tests/out/%P_i12.png
WAIT 25
SCREENSHOT C:/Recomp/PacMan/PacManRecomp/tests/out/%P_i13.png
WAIT 25
SCREENSHOT C:/Recomp/PacMan/PacManRecomp/tests/out/%P_i14.png
WAIT 25
SCREENSHOT C:/Recomp/PacMan/PacManRecomp/tests/out/%P_i15.png
WAIT 25
SCREENSHOT C:/Recomp/PacMan/PacManRecomp/tests/out/%P_i16.png
WAIT 25
SCREENSHOT C:/Recomp/PacMan/PacManRecomp/tests/out/%P_i17.png
WAIT 25
SCREENSHOT C:/Recomp/PacMan/PacManRecomp/tests/out/%P_i18.png
WAIT 25
SCREENSHOT C:/Recomp/PacMan/PacManRecomp/tests/out/%P_i19.png
WAIT 25
SCREENSHOT C:/Recomp/PacMan/PacManRecomp/tests/out/%P_i20.png
WAIT 25
SCREENSHOT C:/Recomp/PacMan/PacManRecomp/tests/out/%P_i21.png
WAIT 25
SCREENSHOT C:/Recomp/PacMan/PacManRecomp/tests/out/%P_i22.png
WAIT 25
SCREENSHOT C:/Recomp/PacMan/PacManRecomp/tests/out/%P_i23.png
WAIT 25
SCREENSHOT C:/Recomp/PacMan/PacManRecomp/tests/out/%P_i24.png
WAIT 25
SCREENSHOT C:/Recomp/PacMan/PacManRecomp/tests/out/%P_i25.png
WAIT 25
SCREENSHOT C:/Recomp/PacMan/PacManRecomp/tests/out/%P_i26.png
WAIT 25
SCREENSHOT C:/Recomp/PacMan/PacManRecomp/tests/out/%P_i27.png
WAIT 25
SCREENSHOT C:/Recomp/PacMan/PacManRecomp/tests/out/%P_i28.png
WAIT 25
SCREENSHOT C:/Recomp/PacMan/PacManRecomp/tests/out/%P_i29.png
WAIT 25
SCREENSHOT C:/Recomp/PacMan/PacManRecomp/tests/out/%P_i30.png
WAIT 25
SCREENSHOT C:/Recomp/PacMan/PacManRecomp/tests/out/%P_i31.png
WAIT 25
SCREENSHOT C:/Recomp/PacMan/PacManRecomp/tests/out/%P_i32.png
WAIT 25
SCREENSHOT C:/Recomp/PacMan/PacManRecomp/tests/out/%P_i33.png
WAIT 25
SCREENSHOT C:/Recomp/PacMan/PacManRecomp/tests/out/%P_i34.png
WAIT 25
SCREENSHOT C:/Recomp/PacMan/PacManRecomp/tests/out/%P_i35.png
WAIT 25
SCREENSHOT C:/Recomp/PacMan/PacManRecomp/tests/out/%P_i36.png
WAIT 25
SCREENSHOT C:/Recomp/PacMan/PacManRecomp/tests/out/%P_i37.png
WAIT 25
SCREENSHOT C:/Recomp/PacMan/PacManRecomp/tests/out/%P_i38.png
WAIT 25
SCREENSHOT C:/Recomp/PacMan/PacManRecomp/tests/out/%P_i39.png
WAIT 25
SCREENSHOT C:/Recomp/PacMan/PacManRecomp/tests/out/%P_i40.png
WAIT 25
SCREENSHOT C:/Recomp/PacMan/PacManRecomp/tests/out/%P_i41.png
WAIT 25
SCREENSHOT C:/Recomp/PacMan/PacManRecomp/tests/out/%P_i42.png
WAIT 25
SCREENSHOT C:/Recomp/PacMan/PacManRecomp/tests/out/%P_i43.png
WAIT 25
SCREENSHOT C:/Recomp/PacMan/PacManRecomp/tests/out/%P_i44.png
WAIT 25
SCREENSHOT C:/Recomp/PacMan/PacManRecomp/tests/out/%P_i45.png
WAIT 25
SCREENSHOT C:/Recomp/PacMan/PacManRecomp/tests/out/%P_i46.png
WAIT 25
SCREENSHOT C:/Recomp/PacMan/PacManRecomp/tests/out/%P_i47.png
WAIT 25
SCREENSHOT C:/Recomp/PacMan/PacManRecomp/tests/out/%P_i48.png
EXIT 0
