#!/usr/bin/env python3
"""
hd_layout_gen.py - turn tools/hd_layout.json into src/hd_layout.h, the table
the game uses to cut beginner graphics (mods/<mod>/graphics/*.png) into
8x8 HD tiles.

Usage: python tools/hd_layout_gen.py
"""
import json
from pathlib import Path

root = Path(__file__).resolve().parent.parent
L = json.loads((root / "tools" / "hd_layout.json").read_text())
m = L["maze"]
out = ["/* src/hd_layout.h - GENERATED by tools/hd_layout_gen.py from",
       " * tools/hd_layout.json. Do not edit by hand. */",
       "#pragma once",
       "#include <stdint.h>",
       "",
       "typedef struct { uint8_t dx, dy, tile, flags; } HdPiece;   /* flags: 1 = H, 2 = V, 4 = shared (owned by an earlier graphic: skip) */",
       "typedef struct {",
       "    const char     *name;       /* file name under graphics/, no .png */",
       "    uint8_t         sprite;     /* 1 = sprite tile (+256), 0 = background */",
       "    uint8_t         w, h;       /* native size in pixels */",
       "    uint8_t         npieces;",
       "    const HdPiece  *pieces;",
       "    uint8_t         npals;",
       "    const uint32_t *pals;       /* color-set keys it is drawn with */",
       "    const char     *mirror_of;  /* fallback when the file is missing */",
       "    char            mirror_axis;/* 'h' / 'v' flip, 'n' = use as-is */",
       "    uint8_t         wild;       /* also register for any color set */",
       "    uint8_t         tint;       /* white art tinted to each color set */",
       "} HdGraphic;",
       "",
       f"#define HD_DEFAULT_SCALE {L['scale']}",
       f"#define HD_MAZE_X {m['x']}",
       f"#define HD_MAZE_Y {m['y']}",
       f"#define HD_MAZE_W {m['cols'] * 8}",
       f"#define HD_MAZE_H {m['rows'] * 8}",
       f"#define HD_MAZE_COND_TILE 0x{m['cond_tile']}",
       f"#define HD_MAZE_PAL_NORMAL 0x{m['pal_normal']}u",
       f"#define HD_MAZE_PAL_FLASH 0x{m['pal_flash']}u",
       "static const uint8_t hd_maze_walls[] = { " + ", ".join("0x" + t for t in m["walls"]) + " };",
       "",
       ]
for i, g in enumerate(L["graphics"]):
    pcs = ", ".join("{%d, %d, 0x%s, %d}" % (p[0], p[1], p[2],
                    (1 if p[3][0] == "H" else 0) | (2 if p[3][1] == "V" else 0) | (4 if p[3][2:] == "S" else 0)) for p in g["pieces"])
    out.append(f"static const HdPiece hd_p{i}[] = {{ {pcs} }};")
    if g["pals"]:
        out.append(f"static const uint32_t hd_c{i}[] = {{ " + ", ".join("0x%su" % c for c in g["pals"]) + " };")
out.append("")
out.append("static const HdGraphic hd_graphics[] = {")
for i, g in enumerate(L["graphics"]):
    mir = g.get("mirror")
    out.append('    { "%s", %d, %d, %d, %d, hd_p%d, %d, %s, %s, %s, %d, %d },' % (
        g["name"], 1 if g["type"] == "sprite" else 0, g["w"], g["h"], len(g["pieces"]), i,
        len(g["pals"]), f"hd_c{i}" if g["pals"] else "0",
        f'"{mir["of"]}"' if mir else "0", f"'{mir['axis']}'" if mir else "0",
        1 if g.get("wild") else 0, 1 if g.get("tint") else 0))
out.append("};")
out.append("#define HD_GRAPHICS_N ((int)(sizeof(hd_graphics) / sizeof(hd_graphics[0])))")
(root / "src" / "hd_layout.h").write_text("\n".join(out) + "\n")
print(f"wrote src/hd_layout.h ({len(L['graphics'])} graphics)")
