/* src/hd_layout.h - GENERATED by tools/hd_layout_gen.py from
 * tools/hd_layout.json. Do not edit by hand. */
#pragma once
#include <stdint.h>

typedef struct { uint8_t dx, dy, tile, flags; } HdPiece;   /* flags: 1 = H, 2 = V */
typedef struct {
    const char     *name;       /* file name under graphics/, no .png */
    uint8_t         sprite;     /* 1 = sprite tile (+256), 0 = background */
    uint8_t         w, h;       /* native size in pixels */
    uint8_t         npieces;
    const HdPiece  *pieces;
    uint8_t         npals;
    const uint32_t *pals;       /* color-set keys it is drawn with */
    const char     *mirror_of;  /* fallback when the file is missing */
    char            mirror_axis;/* 'h' / 'v' flip, 'n' = use as-is */
    uint8_t         wild;       /* also register for any color set */
    uint8_t         tint;       /* white art tinted to each color set */
} HdGraphic;

#define HD_DEFAULT_SCALE 4
#define HD_MAZE_X 8
#define HD_MAZE_Y 16
#define HD_MAZE_W 168
#define HD_MAZE_H 216
#define HD_MAZE_COND_TILE 0x1F
#define HD_MAZE_PAL_NORMAL 0x0F110F27u
#define HD_MAZE_PAL_FLASH 0x0F200F27u
static const uint8_t hd_maze_walls[] = { 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1A, 0x1B, 0x1C, 0x1D, 0x1E, 0x1F, 0x21, 0x22, 0x2C };

static const HdPiece hd_p0[] = { {0, 0, 0x00, 0}, {8, 0, 0x00, 1}, {0, 8, 0x00, 2}, {8, 8, 0x00, 3} };
static const uint32_t hd_c0[] = { 0xFF272006u };
static const HdPiece hd_p1[] = { {0, 0, 0x02, 0}, {8, 0, 0x01, 0}, {0, 8, 0x02, 2}, {8, 8, 0x01, 2} };
static const uint32_t hd_c1[] = { 0xFF272006u };
static const HdPiece hd_p2[] = { {0, 0, 0x06, 0}, {8, 0, 0x05, 0}, {0, 8, 0x06, 2}, {8, 8, 0x05, 2} };
static const uint32_t hd_c2[] = { 0xFF272006u };
static const HdPiece hd_p3[] = { {0, 0, 0x01, 1}, {8, 0, 0x02, 1}, {0, 8, 0x01, 3}, {8, 8, 0x02, 3} };
static const uint32_t hd_c3[] = { 0xFF272006u };
static const HdPiece hd_p4[] = { {0, 0, 0x05, 1}, {8, 0, 0x06, 1}, {0, 8, 0x05, 3}, {8, 8, 0x06, 3} };
static const uint32_t hd_c4[] = { 0xFF272006u };
static const HdPiece hd_p5[] = { {0, 0, 0x03, 0}, {8, 0, 0x03, 1}, {0, 8, 0x04, 0}, {8, 8, 0x04, 1} };
static const uint32_t hd_c5[] = { 0xFF272006u };
static const HdPiece hd_p6[] = { {0, 0, 0x07, 0}, {8, 0, 0x07, 1}, {0, 8, 0x08, 0}, {8, 8, 0x08, 1} };
static const uint32_t hd_c6[] = { 0xFF272006u };
static const HdPiece hd_p7[] = { {0, 0, 0x04, 2}, {8, 0, 0x04, 3}, {0, 8, 0x03, 2}, {8, 8, 0x03, 3} };
static const uint32_t hd_c7[] = { 0xFF272006u };
static const HdPiece hd_p8[] = { {0, 0, 0x08, 2}, {8, 0, 0x08, 3}, {0, 8, 0x07, 2}, {8, 8, 0x07, 3} };
static const uint32_t hd_c8[] = { 0xFF272006u };
static const HdPiece hd_p9[] = { {0, 0, 0x09, 0}, {8, 0, 0x09, 1}, {0, 8, 0x0A, 0}, {8, 8, 0x0A, 1} };
static const uint32_t hd_c9[] = { 0xFF272006u };
static const HdPiece hd_p10[] = { {0, 0, 0x0B, 0}, {8, 0, 0x0B, 1}, {0, 8, 0x0C, 0}, {8, 8, 0x0C, 1} };
static const uint32_t hd_c10[] = { 0xFF272006u };
static const HdPiece hd_p11[] = { {0, 0, 0x4C, 0}, {8, 0, 0x4C, 0}, {0, 8, 0x0D, 0}, {8, 8, 0x0D, 1} };
static const uint32_t hd_c11[] = { 0xFF272006u };
static const HdPiece hd_p12[] = { {0, 0, 0x4C, 0}, {8, 0, 0x4C, 0}, {0, 8, 0x0E, 0}, {8, 8, 0x0E, 1} };
static const uint32_t hd_c12[] = { 0xFF272006u };
static const HdPiece hd_p13[] = { {0, 0, 0x4C, 0}, {8, 0, 0x4C, 0}, {0, 8, 0x0F, 0}, {8, 8, 0x0F, 1} };
static const uint32_t hd_c13[] = { 0xFF272006u };
static const HdPiece hd_p14[] = { {0, 0, 0x4C, 0}, {8, 0, 0x4C, 0}, {0, 8, 0x10, 0}, {8, 8, 0x10, 1} };
static const uint32_t hd_c14[] = { 0xFF272006u };
static const HdPiece hd_p15[] = { {0, 0, 0x4C, 0}, {8, 0, 0x4C, 0}, {0, 8, 0x11, 0}, {8, 8, 0x11, 1} };
static const uint32_t hd_c15[] = { 0xFF272006u };
static const HdPiece hd_p16[] = { {0, 0, 0x4C, 0}, {8, 0, 0x4C, 0}, {0, 8, 0x12, 0}, {8, 8, 0x12, 1} };
static const uint32_t hd_c16[] = { 0xFF272006u };
static const HdPiece hd_p17[] = { {0, 0, 0x14, 0}, {8, 0, 0x15, 0}, {0, 8, 0x16, 0}, {8, 8, 0x17, 0} };
static const uint32_t hd_c17[] = { 0xFF272006u };
static const HdPiece hd_p18[] = { {0, 0, 0x18, 0}, {8, 0, 0x18, 1}, {0, 8, 0x19, 0}, {8, 8, 0x19, 1} };
static const uint32_t hd_c18[] = { 0xFF272006u };
static const HdPiece hd_p19[] = { {0, 0, 0x18, 0}, {8, 0, 0x18, 1}, {0, 8, 0x1A, 0}, {8, 8, 0x1A, 1} };
static const uint32_t hd_c19[] = { 0xFF272006u };
static const HdPiece hd_p20[] = { {0, 0, 0x1B, 0}, {8, 0, 0x1C, 0}, {0, 8, 0x1D, 0}, {8, 8, 0x1F, 0} };
static const uint32_t hd_c20[] = { 0xFF272006u, 0xFF362006u };
static const HdPiece hd_p21[] = { {0, 0, 0x1B, 0}, {8, 0, 0x1C, 0}, {0, 8, 0x1E, 0}, {8, 8, 0x20, 0} };
static const uint32_t hd_c21[] = { 0xFF272006u, 0xFF362006u };
static const HdPiece hd_p22[] = { {0, 0, 0x1C, 1}, {8, 0, 0x1B, 1}, {0, 8, 0x1F, 1}, {8, 8, 0x1D, 1} };
static const uint32_t hd_c22[] = { 0xFF272006u };
static const HdPiece hd_p23[] = { {0, 0, 0x1C, 1}, {8, 0, 0x1B, 1}, {0, 8, 0x20, 1}, {8, 8, 0x1E, 1} };
static const uint32_t hd_c23[] = { 0xFF272006u };
static const HdPiece hd_p24[] = { {0, 0, 0x21, 0}, {8, 0, 0x21, 1}, {0, 8, 0x22, 0}, {8, 8, 0x22, 1} };
static const uint32_t hd_c24[] = { 0xFF272006u };
static const HdPiece hd_p25[] = { {0, 0, 0x21, 0}, {8, 0, 0x21, 1}, {0, 8, 0x23, 0}, {8, 8, 0x23, 1} };
static const uint32_t hd_c25[] = { 0xFF272006u };
static const HdPiece hd_p26[] = { {0, 0, 0x18, 0}, {8, 0, 0x18, 1}, {0, 8, 0x19, 0}, {8, 8, 0x19, 1} };
static const uint32_t hd_c26[] = { 0xFF112033u, 0xFF202033u };
static const HdPiece hd_p27[] = { {0, 0, 0x18, 0}, {8, 0, 0x18, 1}, {0, 8, 0x1A, 0}, {8, 8, 0x1A, 1} };
static const uint32_t hd_c27[] = { 0xFF112033u, 0xFF202033u };
static const HdPiece hd_p28[] = { {0, 0, 0x1B, 0}, {8, 0, 0x1C, 0}, {0, 8, 0x1D, 0}, {8, 8, 0x1F, 0} };
static const uint32_t hd_c28[] = { 0xFF112033u, 0xFF202033u };
static const HdPiece hd_p29[] = { {0, 0, 0x1B, 0}, {8, 0, 0x1C, 0}, {0, 8, 0x1E, 0}, {8, 8, 0x20, 0} };
static const uint32_t hd_c29[] = { 0xFF112033u, 0xFF202033u };
static const HdPiece hd_p30[] = { {0, 0, 0x1C, 1}, {8, 0, 0x1B, 1}, {0, 8, 0x1F, 1}, {8, 8, 0x1D, 1} };
static const uint32_t hd_c30[] = { 0xFF112033u, 0xFF202033u };
static const HdPiece hd_p31[] = { {0, 0, 0x1C, 1}, {8, 0, 0x1B, 1}, {0, 8, 0x20, 1}, {8, 8, 0x1E, 1} };
static const uint32_t hd_c31[] = { 0xFF112033u, 0xFF202033u };
static const HdPiece hd_p32[] = { {0, 0, 0x21, 0}, {8, 0, 0x21, 1}, {0, 8, 0x22, 0}, {8, 8, 0x22, 1} };
static const uint32_t hd_c32[] = { 0xFF112033u };
static const HdPiece hd_p33[] = { {0, 0, 0x21, 0}, {8, 0, 0x21, 1}, {0, 8, 0x23, 0}, {8, 8, 0x23, 1} };
static const uint32_t hd_c33[] = { 0xFF112033u };
static const HdPiece hd_p34[] = { {0, 0, 0x18, 0}, {8, 0, 0x18, 1}, {0, 8, 0x19, 0}, {8, 8, 0x19, 1} };
static const uint32_t hd_c34[] = { 0xFF212021u };
static const HdPiece hd_p35[] = { {0, 0, 0x18, 0}, {8, 0, 0x18, 1}, {0, 8, 0x1A, 0}, {8, 8, 0x1A, 1} };
static const uint32_t hd_c35[] = { 0xFF212021u };
static const HdPiece hd_p36[] = { {0, 0, 0x1B, 0}, {8, 0, 0x1C, 0}, {0, 8, 0x1D, 0}, {8, 8, 0x1F, 0} };
static const uint32_t hd_c36[] = { 0xFF202021u, 0xFF212021u };
static const HdPiece hd_p37[] = { {0, 0, 0x1B, 0}, {8, 0, 0x1C, 0}, {0, 8, 0x1E, 0}, {8, 8, 0x20, 0} };
static const uint32_t hd_c37[] = { 0xFF202021u, 0xFF212021u };
static const HdPiece hd_p38[] = { {0, 0, 0x1C, 1}, {8, 0, 0x1B, 1}, {0, 8, 0x1F, 1}, {8, 8, 0x1D, 1} };
static const uint32_t hd_c38[] = { 0xFF202021u, 0xFF212021u };
static const HdPiece hd_p39[] = { {0, 0, 0x1C, 1}, {8, 0, 0x1B, 1}, {0, 8, 0x20, 1}, {8, 8, 0x1E, 1} };
static const uint32_t hd_c39[] = { 0xFF212021u };
static const HdPiece hd_p40[] = { {0, 0, 0x21, 0}, {8, 0, 0x21, 1}, {0, 8, 0x22, 0}, {8, 8, 0x22, 1} };
static const uint32_t hd_c40[] = { 0xFF212021u };
static const HdPiece hd_p41[] = { {0, 0, 0x21, 0}, {8, 0, 0x21, 1}, {0, 8, 0x23, 0}, {8, 8, 0x23, 1} };
static const uint32_t hd_c41[] = { 0xFF212021u };
static const HdPiece hd_p42[] = { {0, 0, 0x18, 0}, {8, 0, 0x18, 1}, {0, 8, 0x19, 0}, {8, 8, 0x19, 1} };
static const uint32_t hd_c42[] = { 0xFF062017u, 0xFF122017u, 0xFF162017u, 0xFF172017u, 0xFF192017u, 0xFF262017u };
static const HdPiece hd_p43[] = { {0, 0, 0x18, 0}, {8, 0, 0x18, 1}, {0, 8, 0x1A, 0}, {8, 8, 0x1A, 1} };
static const uint32_t hd_c43[] = { 0xFF062017u, 0xFF122017u, 0xFF162017u, 0xFF172017u, 0xFF192017u, 0xFF262017u };
static const HdPiece hd_p44[] = { {0, 0, 0x1B, 0}, {8, 0, 0x1C, 0}, {0, 8, 0x1D, 0}, {8, 8, 0x1F, 0} };
static const uint32_t hd_c44[] = { 0xFF062017u, 0xFF092017u, 0xFF122017u, 0xFF162017u, 0xFF172017u, 0xFF192017u, 0xFF262017u };
static const HdPiece hd_p45[] = { {0, 0, 0x1B, 0}, {8, 0, 0x1C, 0}, {0, 8, 0x1E, 0}, {8, 8, 0x20, 0} };
static const uint32_t hd_c45[] = { 0xFF062017u, 0xFF092017u, 0xFF122017u, 0xFF162017u, 0xFF172017u, 0xFF192017u, 0xFF262017u };
static const HdPiece hd_p46[] = { {0, 0, 0x1C, 1}, {8, 0, 0x1B, 1}, {0, 8, 0x1F, 1}, {8, 8, 0x1D, 1} };
static const uint32_t hd_c46[] = { 0xFF062017u, 0xFF092017u, 0xFF122017u, 0xFF162017u, 0xFF172017u, 0xFF192017u, 0xFF262017u };
static const HdPiece hd_p47[] = { {0, 0, 0x1C, 1}, {8, 0, 0x1B, 1}, {0, 8, 0x20, 1}, {8, 8, 0x1E, 1} };
static const uint32_t hd_c47[] = { 0xFF062017u, 0xFF122017u, 0xFF162017u, 0xFF172017u, 0xFF192017u, 0xFF262017u };
static const HdPiece hd_p48[] = { {0, 0, 0x21, 0}, {8, 0, 0x21, 1}, {0, 8, 0x22, 0}, {8, 8, 0x22, 1} };
static const uint32_t hd_c48[] = { 0xFF062017u, 0xFF122017u, 0xFF162017u, 0xFF172017u, 0xFF192017u, 0xFF262017u };
static const HdPiece hd_p49[] = { {0, 0, 0x21, 0}, {8, 0, 0x21, 1}, {0, 8, 0x23, 0}, {8, 8, 0x23, 1} };
static const uint32_t hd_c49[] = { 0xFF062017u, 0xFF122017u, 0xFF162017u, 0xFF172017u, 0xFF192017u, 0xFF262017u };
static const HdPiece hd_p50[] = { {0, 0, 0x24, 0}, {8, 0, 0x24, 1}, {0, 8, 0x25, 0}, {8, 8, 0x25, 1} };
static const uint32_t hd_c50[] = { 0xFF112033u };
static const HdPiece hd_p51[] = { {0, 0, 0x24, 0}, {8, 0, 0x24, 1}, {0, 8, 0x25, 0}, {8, 8, 0x25, 1} };
static const uint32_t hd_c51[] = { 0xFF202033u };
static const HdPiece hd_p52[] = { {0, 0, 0x24, 0}, {8, 0, 0x24, 1}, {0, 8, 0x26, 0}, {8, 8, 0x26, 1} };
static const uint32_t hd_c52[] = { 0xFF112033u };
static const HdPiece hd_p53[] = { {0, 0, 0x24, 0}, {8, 0, 0x24, 1}, {0, 8, 0x26, 0}, {8, 8, 0x26, 1} };
static const uint32_t hd_c53[] = { 0xFF202033u };
static const HdPiece hd_p54[] = { {0, 0, 0x27, 0}, {8, 0, 0x27, 1}, {0, 8, 0x4C, 0}, {8, 8, 0x4C, 0} };
static const uint32_t hd_c54[] = { 0xFF112033u, 0xFF202033u };
static const HdPiece hd_p55[] = { {0, 0, 0x28, 0}, {8, 0, 0x29, 0}, {0, 8, 0x2A, 0}, {8, 8, 0x2B, 0} };
static const uint32_t hd_c55[] = { 0xFF112033u, 0xFF202033u };
static const HdPiece hd_p56[] = { {0, 0, 0x29, 1}, {8, 0, 0x28, 1}, {0, 8, 0x2B, 1}, {8, 8, 0x2A, 1} };
static const uint32_t hd_c56[] = { 0xFF112033u, 0xFF202033u };
static const HdPiece hd_p57[] = { {0, 0, 0x2C, 0}, {8, 0, 0x2C, 1}, {0, 8, 0x2D, 0}, {8, 8, 0x2D, 1} };
static const uint32_t hd_c57[] = { 0xFF112033u, 0xFF202033u, 0xFF272006u };
static const HdPiece hd_p58[] = { {0, 0, 0x90, 0}, {8, 0, 0x91, 0}, {0, 8, 0x92, 0}, {8, 8, 0x93, 0} };
static const uint32_t hd_c58[] = { 0xFF162017u };
static const HdPiece hd_p59[] = { {0, 0, 0x94, 0}, {8, 0, 0x95, 0}, {0, 8, 0x96, 0}, {8, 8, 0x97, 0} };
static const uint32_t hd_c59[] = { 0xFF162017u };
static const HdPiece hd_p60[] = { {0, 0, 0x98, 0}, {8, 0, 0x99, 0}, {0, 8, 0x9A, 0}, {8, 8, 0x9B, 0} };
static const uint32_t hd_c60[] = { 0xFF262017u };
static const HdPiece hd_p61[] = { {0, 0, 0x9C, 0}, {8, 0, 0x9D, 0}, {0, 8, 0x9E, 0}, {8, 8, 0x9F, 0} };
static const uint32_t hd_c61[] = { 0xFF062017u };
static const HdPiece hd_p62[] = { {0, 0, 0xA0, 0}, {8, 0, 0xA1, 0}, {0, 8, 0xA2, 0}, {8, 8, 0xA3, 0} };
static const uint32_t hd_c62[] = { 0xFF192017u };
static const HdPiece hd_p63[] = { {0, 0, 0xA4, 0}, {8, 0, 0xA5, 0}, {0, 8, 0xA6, 0}, {8, 8, 0xA7, 0} };
static const uint32_t hd_c63[] = { 0xFF172017u };
static const HdPiece hd_p64[] = { {0, 0, 0xA8, 0}, {8, 0, 0xA9, 0}, {0, 8, 0xAA, 0}, {8, 8, 0xAB, 0} };
static const uint32_t hd_c64[] = { 0xFF172017u };
static const HdPiece hd_p65[] = { {0, 0, 0xAC, 0}, {8, 0, 0xAD, 0}, {0, 8, 0xAE, 0}, {8, 8, 0xAF, 0} };
static const uint32_t hd_c65[] = { 0xFF122017u };
static const HdPiece hd_p66[] = { {0, 0, 0x2E, 0}, {8, 0, 0x2F, 0}, {0, 8, 0x30, 0}, {8, 8, 0x31, 0} };
static const uint32_t hd_c66[] = { 0xFF162017u };
static const HdPiece hd_p67[] = { {0, 0, 0x32, 0}, {8, 0, 0x2F, 0}, {0, 8, 0x33, 0}, {8, 8, 0x31, 0} };
static const uint32_t hd_c67[] = { 0xFF112033u, 0xFF272006u };
static const HdPiece hd_p68[] = { {0, 0, 0x36, 0}, {8, 0, 0x2F, 0}, {0, 8, 0x37, 0}, {8, 8, 0x31, 0} };
static const uint32_t hd_c68[] = { 0xFF112033u, 0xFF272006u };
static const HdPiece hd_p69[] = { {0, 0, 0x3C, 0}, {8, 0, 0x2F, 0}, {0, 8, 0x3D, 0}, {8, 8, 0x31, 0} };
static const uint32_t hd_c69[] = { 0xFF272006u };
static const HdPiece hd_p70[] = { {0, 0, 0x42, 0}, {8, 0, 0x3F, 0}, {0, 8, 0x43, 0}, {8, 8, 0x41, 0} };
static const uint32_t hd_c70[] = { 0xFF272006u };
static const HdPiece hd_p71[] = { {0, 0, 0x60, 0}, {8, 0, 0x61, 0}, {0, 8, 0x62, 0}, {8, 8, 0x63, 0} };
static const HdPiece hd_p72[] = { {0, 0, 0x64, 0}, {8, 0, 0x65, 0}, {0, 8, 0x66, 0}, {8, 8, 0x67, 0} };
static const HdPiece hd_p73[] = { {0, 0, 0x68, 0}, {8, 0, 0x69, 0}, {0, 8, 0x6A, 0}, {8, 8, 0x6B, 0} };
static const HdPiece hd_p74[] = { {0, 0, 0x6C, 0}, {8, 0, 0x6D, 0}, {0, 8, 0x6E, 0}, {8, 8, 0x6F, 0} };
static const HdPiece hd_p75[] = { {0, 0, 0x70, 0}, {8, 0, 0x71, 0}, {0, 8, 0x72, 0}, {8, 8, 0x73, 0} };
static const HdPiece hd_p76[] = { {0, 0, 0x74, 0}, {8, 0, 0x75, 0}, {0, 8, 0x76, 0}, {8, 8, 0x77, 0} };
static const HdPiece hd_p77[] = { {0, 0, 0x78, 0}, {8, 0, 0x79, 0}, {0, 8, 0x7A, 0}, {8, 8, 0x7B, 0} };
static const HdPiece hd_p78[] = { {0, 0, 0x7C, 0}, {8, 0, 0x7D, 0}, {0, 8, 0x7E, 0}, {8, 8, 0x7F, 0} };
static const HdPiece hd_p79[] = { {0, 0, 0x3C, 0}, {8, 0, 0x3D, 0}, {0, 8, 0x3E, 0}, {8, 8, 0x3F, 0} };
static const HdPiece hd_p80[] = { {0, 0, 0x03, 0} };
static const HdPiece hd_p81[] = { {0, 0, 0x09, 0} };
static const HdPiece hd_p82[] = { {0, 0, 0x01, 0} };
static const HdPiece hd_p83[] = { {0, 0, 0x41, 0} };
static const uint32_t hd_c83[] = { 0x0F060F33u, 0x0F170F21u, 0x0F200F06u, 0x0F330F27u };
static const HdPiece hd_p84[] = { {0, 0, 0x42, 0} };
static const uint32_t hd_c84[] = { 0x0F060F33u, 0x0F170F21u, 0x0F200F06u, 0x0F330F27u };
static const HdPiece hd_p85[] = { {0, 0, 0x43, 0} };
static const uint32_t hd_c85[] = { 0x0F060F33u, 0x0F170F21u, 0x0F200F06u, 0x0F330F27u };
static const HdPiece hd_p86[] = { {0, 0, 0x44, 0} };
static const uint32_t hd_c86[] = { 0x0F060F33u, 0x0F170F21u, 0x0F200F06u, 0x0F330F27u };
static const HdPiece hd_p87[] = { {0, 0, 0x45, 0} };
static const uint32_t hd_c87[] = { 0x0F060F33u, 0x0F170F21u, 0x0F200F06u, 0x0F330F27u };
static const HdPiece hd_p88[] = { {0, 0, 0x46, 0} };
static const uint32_t hd_c88[] = { 0x0F060F33u, 0x0F170F21u, 0x0F200F06u, 0x0F330F27u };
static const HdPiece hd_p89[] = { {0, 0, 0x47, 0} };
static const uint32_t hd_c89[] = { 0x0F060F33u, 0x0F170F21u, 0x0F200F06u, 0x0F330F27u };
static const HdPiece hd_p90[] = { {0, 0, 0x48, 0} };
static const uint32_t hd_c90[] = { 0x0F060F33u, 0x0F170F21u, 0x0F200F06u, 0x0F330F27u };
static const HdPiece hd_p91[] = { {0, 0, 0x49, 0} };
static const uint32_t hd_c91[] = { 0x0F060F33u, 0x0F170F21u, 0x0F200F06u, 0x0F330F27u };
static const HdPiece hd_p92[] = { {0, 0, 0x4A, 0} };
static const uint32_t hd_c92[] = { 0x0F060F33u, 0x0F170F21u, 0x0F200F06u, 0x0F330F27u };
static const HdPiece hd_p93[] = { {0, 0, 0x4B, 0} };
static const uint32_t hd_c93[] = { 0x0F060F33u, 0x0F170F21u, 0x0F200F06u, 0x0F330F27u };
static const HdPiece hd_p94[] = { {0, 0, 0x4C, 0} };
static const uint32_t hd_c94[] = { 0x0F060F33u, 0x0F170F21u, 0x0F200F06u, 0x0F330F27u };
static const HdPiece hd_p95[] = { {0, 0, 0x4D, 0} };
static const uint32_t hd_c95[] = { 0x0F060F33u, 0x0F170F21u, 0x0F200F06u, 0x0F330F27u };
static const HdPiece hd_p96[] = { {0, 0, 0x4E, 0} };
static const uint32_t hd_c96[] = { 0x0F060F33u, 0x0F170F21u, 0x0F200F06u, 0x0F330F27u };
static const HdPiece hd_p97[] = { {0, 0, 0x4F, 0} };
static const uint32_t hd_c97[] = { 0x0F060F33u, 0x0F170F21u, 0x0F200F06u, 0x0F330F27u };
static const HdPiece hd_p98[] = { {0, 0, 0x50, 0} };
static const uint32_t hd_c98[] = { 0x0F060F33u, 0x0F170F21u, 0x0F200F06u, 0x0F330F27u };
static const HdPiece hd_p99[] = { {0, 0, 0x51, 0} };
static const uint32_t hd_c99[] = { 0x0F060F33u, 0x0F170F21u, 0x0F200F06u, 0x0F330F27u };
static const HdPiece hd_p100[] = { {0, 0, 0x52, 0} };
static const uint32_t hd_c100[] = { 0x0F060F33u, 0x0F170F21u, 0x0F200F06u, 0x0F330F27u };
static const HdPiece hd_p101[] = { {0, 0, 0x53, 0} };
static const uint32_t hd_c101[] = { 0x0F060F33u, 0x0F170F21u, 0x0F200F06u, 0x0F330F27u };
static const HdPiece hd_p102[] = { {0, 0, 0x54, 0} };
static const uint32_t hd_c102[] = { 0x0F060F33u, 0x0F170F21u, 0x0F200F06u, 0x0F330F27u };
static const HdPiece hd_p103[] = { {0, 0, 0x55, 0} };
static const uint32_t hd_c103[] = { 0x0F060F33u, 0x0F170F21u, 0x0F200F06u, 0x0F330F27u };
static const HdPiece hd_p104[] = { {0, 0, 0x56, 0} };
static const uint32_t hd_c104[] = { 0x0F060F33u, 0x0F170F21u, 0x0F200F06u, 0x0F330F27u };
static const HdPiece hd_p105[] = { {0, 0, 0x57, 0} };
static const uint32_t hd_c105[] = { 0x0F060F33u, 0x0F170F21u, 0x0F200F06u, 0x0F330F27u };
static const HdPiece hd_p106[] = { {0, 0, 0x58, 0} };
static const uint32_t hd_c106[] = { 0x0F060F33u, 0x0F170F21u, 0x0F200F06u, 0x0F330F27u };
static const HdPiece hd_p107[] = { {0, 0, 0x59, 0} };
static const uint32_t hd_c107[] = { 0x0F060F33u, 0x0F170F21u, 0x0F200F06u, 0x0F330F27u };
static const HdPiece hd_p108[] = { {0, 0, 0x5A, 0} };
static const uint32_t hd_c108[] = { 0x0F060F33u, 0x0F170F21u, 0x0F200F06u, 0x0F330F27u };
static const HdPiece hd_p109[] = { {0, 0, 0x30, 0} };
static const uint32_t hd_c109[] = { 0x0F060F33u, 0x0F170F21u, 0x0F200F06u, 0x0F330F27u };
static const HdPiece hd_p110[] = { {0, 0, 0x31, 0} };
static const uint32_t hd_c110[] = { 0x0F060F33u, 0x0F170F21u, 0x0F200F06u, 0x0F330F27u };
static const HdPiece hd_p111[] = { {0, 0, 0x32, 0} };
static const uint32_t hd_c111[] = { 0x0F060F33u, 0x0F170F21u, 0x0F200F06u, 0x0F330F27u };
static const HdPiece hd_p112[] = { {0, 0, 0x33, 0} };
static const uint32_t hd_c112[] = { 0x0F060F33u, 0x0F170F21u, 0x0F200F06u, 0x0F330F27u };
static const HdPiece hd_p113[] = { {0, 0, 0x34, 0} };
static const uint32_t hd_c113[] = { 0x0F060F33u, 0x0F170F21u, 0x0F200F06u, 0x0F330F27u };
static const HdPiece hd_p114[] = { {0, 0, 0x35, 0} };
static const uint32_t hd_c114[] = { 0x0F060F33u, 0x0F170F21u, 0x0F200F06u, 0x0F330F27u };
static const HdPiece hd_p115[] = { {0, 0, 0x36, 0} };
static const uint32_t hd_c115[] = { 0x0F060F33u, 0x0F170F21u, 0x0F200F06u, 0x0F330F27u };
static const HdPiece hd_p116[] = { {0, 0, 0x37, 0} };
static const uint32_t hd_c116[] = { 0x0F060F33u, 0x0F170F21u, 0x0F200F06u, 0x0F330F27u };
static const HdPiece hd_p117[] = { {0, 0, 0x38, 0} };
static const uint32_t hd_c117[] = { 0x0F060F33u, 0x0F170F21u, 0x0F200F06u, 0x0F330F27u };
static const HdPiece hd_p118[] = { {0, 0, 0x39, 0} };
static const uint32_t hd_c118[] = { 0x0F060F33u, 0x0F170F21u, 0x0F200F06u, 0x0F330F27u };
static const HdPiece hd_p119[] = { {0, 0, 0x3A, 0} };
static const uint32_t hd_c119[] = { 0x0F060F33u, 0x0F170F21u, 0x0F200F06u, 0x0F330F27u };
static const HdPiece hd_p120[] = { {0, 0, 0x5B, 0} };
static const uint32_t hd_c120[] = { 0x0F060F33u, 0x0F170F21u, 0x0F200F06u, 0x0F330F27u };
static const HdPiece hd_p121[] = { {0, 0, 0x5C, 0} };
static const uint32_t hd_c121[] = { 0x0F060F33u, 0x0F170F21u, 0x0F200F06u, 0x0F330F27u };
static const HdPiece hd_p122[] = { {0, 0, 0x5D, 0} };
static const uint32_t hd_c122[] = { 0x0F060F33u, 0x0F170F21u, 0x0F200F06u, 0x0F330F27u };

static const HdGraphic hd_graphics[] = {
    { "pacman/closed", 1, 16, 16, 4, hd_p0, 1, hd_c0, 0, 0, 1, 0 },
    { "pacman/right_1", 1, 16, 16, 4, hd_p1, 1, hd_c1, 0, 0, 1, 0 },
    { "pacman/right_2", 1, 16, 16, 4, hd_p2, 1, hd_c2, 0, 0, 1, 0 },
    { "pacman/left_1", 1, 16, 16, 4, hd_p3, 1, hd_c3, "pacman/right_1", 'h', 1, 0 },
    { "pacman/left_2", 1, 16, 16, 4, hd_p4, 1, hd_c4, "pacman/right_2", 'h', 1, 0 },
    { "pacman/down_1", 1, 16, 16, 4, hd_p5, 1, hd_c5, 0, 0, 1, 0 },
    { "pacman/down_2", 1, 16, 16, 4, hd_p6, 1, hd_c6, 0, 0, 1, 0 },
    { "pacman/up_1", 1, 16, 16, 4, hd_p7, 1, hd_c7, "pacman/down_1", 'v', 1, 0 },
    { "pacman/up_2", 1, 16, 16, 4, hd_p8, 1, hd_c8, "pacman/down_2", 'v', 1, 0 },
    { "pacman/death_1", 1, 16, 16, 4, hd_p9, 1, hd_c9, 0, 0, 1, 0 },
    { "pacman/death_2", 1, 16, 16, 4, hd_p10, 1, hd_c10, 0, 0, 1, 0 },
    { "pacman/death_3", 1, 16, 16, 4, hd_p11, 1, hd_c11, 0, 0, 1, 0 },
    { "pacman/death_4", 1, 16, 16, 4, hd_p12, 1, hd_c12, 0, 0, 1, 0 },
    { "pacman/death_5", 1, 16, 16, 4, hd_p13, 1, hd_c13, 0, 0, 1, 0 },
    { "pacman/death_6", 1, 16, 16, 4, hd_p14, 1, hd_c14, 0, 0, 1, 0 },
    { "pacman/death_7", 1, 16, 16, 4, hd_p15, 1, hd_c15, 0, 0, 1, 0 },
    { "pacman/death_8", 1, 16, 16, 4, hd_p16, 1, hd_c16, 0, 0, 1, 0 },
    { "pacman/death_9", 1, 16, 16, 4, hd_p17, 1, hd_c17, 0, 0, 1, 0 },
    { "ghosts/blinky/down_1", 1, 16, 16, 4, hd_p18, 1, hd_c18, 0, 0, 0, 0 },
    { "ghosts/blinky/down_2", 1, 16, 16, 4, hd_p19, 1, hd_c19, 0, 0, 0, 0 },
    { "ghosts/blinky/right_1", 1, 16, 16, 4, hd_p20, 2, hd_c20, 0, 0, 0, 0 },
    { "ghosts/blinky/right_2", 1, 16, 16, 4, hd_p21, 2, hd_c21, 0, 0, 0, 0 },
    { "ghosts/blinky/left_1", 1, 16, 16, 4, hd_p22, 1, hd_c22, "ghosts/blinky/right_1", 'h', 0, 0 },
    { "ghosts/blinky/left_2", 1, 16, 16, 4, hd_p23, 1, hd_c23, "ghosts/blinky/right_2", 'h', 0, 0 },
    { "ghosts/blinky/up_1", 1, 16, 16, 4, hd_p24, 1, hd_c24, 0, 0, 0, 0 },
    { "ghosts/blinky/up_2", 1, 16, 16, 4, hd_p25, 1, hd_c25, 0, 0, 0, 0 },
    { "ghosts/pinky/down_1", 1, 16, 16, 4, hd_p26, 2, hd_c26, 0, 0, 0, 0 },
    { "ghosts/pinky/down_2", 1, 16, 16, 4, hd_p27, 2, hd_c27, 0, 0, 0, 0 },
    { "ghosts/pinky/right_1", 1, 16, 16, 4, hd_p28, 2, hd_c28, 0, 0, 0, 0 },
    { "ghosts/pinky/right_2", 1, 16, 16, 4, hd_p29, 2, hd_c29, 0, 0, 0, 0 },
    { "ghosts/pinky/left_1", 1, 16, 16, 4, hd_p30, 2, hd_c30, "ghosts/pinky/right_1", 'h', 0, 0 },
    { "ghosts/pinky/left_2", 1, 16, 16, 4, hd_p31, 2, hd_c31, "ghosts/pinky/right_2", 'h', 0, 0 },
    { "ghosts/pinky/up_1", 1, 16, 16, 4, hd_p32, 1, hd_c32, 0, 0, 0, 0 },
    { "ghosts/pinky/up_2", 1, 16, 16, 4, hd_p33, 1, hd_c33, 0, 0, 0, 0 },
    { "ghosts/inky/down_1", 1, 16, 16, 4, hd_p34, 1, hd_c34, 0, 0, 0, 0 },
    { "ghosts/inky/down_2", 1, 16, 16, 4, hd_p35, 1, hd_c35, 0, 0, 0, 0 },
    { "ghosts/inky/right_1", 1, 16, 16, 4, hd_p36, 2, hd_c36, 0, 0, 0, 0 },
    { "ghosts/inky/right_2", 1, 16, 16, 4, hd_p37, 2, hd_c37, 0, 0, 0, 0 },
    { "ghosts/inky/left_1", 1, 16, 16, 4, hd_p38, 2, hd_c38, "ghosts/inky/right_1", 'h', 0, 0 },
    { "ghosts/inky/left_2", 1, 16, 16, 4, hd_p39, 1, hd_c39, "ghosts/inky/right_2", 'h', 0, 0 },
    { "ghosts/inky/up_1", 1, 16, 16, 4, hd_p40, 1, hd_c40, 0, 0, 0, 0 },
    { "ghosts/inky/up_2", 1, 16, 16, 4, hd_p41, 1, hd_c41, 0, 0, 0, 0 },
    { "ghosts/clyde/down_1", 1, 16, 16, 4, hd_p42, 6, hd_c42, 0, 0, 0, 0 },
    { "ghosts/clyde/down_2", 1, 16, 16, 4, hd_p43, 6, hd_c43, 0, 0, 0, 0 },
    { "ghosts/clyde/right_1", 1, 16, 16, 4, hd_p44, 7, hd_c44, 0, 0, 0, 0 },
    { "ghosts/clyde/right_2", 1, 16, 16, 4, hd_p45, 7, hd_c45, 0, 0, 0, 0 },
    { "ghosts/clyde/left_1", 1, 16, 16, 4, hd_p46, 7, hd_c46, "ghosts/clyde/right_1", 'h', 0, 0 },
    { "ghosts/clyde/left_2", 1, 16, 16, 4, hd_p47, 6, hd_c47, "ghosts/clyde/right_2", 'h', 0, 0 },
    { "ghosts/clyde/up_1", 1, 16, 16, 4, hd_p48, 6, hd_c48, 0, 0, 0, 0 },
    { "ghosts/clyde/up_2", 1, 16, 16, 4, hd_p49, 6, hd_c49, 0, 0, 0, 0 },
    { "ghosts/frightened/blue_1", 1, 16, 16, 4, hd_p50, 1, hd_c50, 0, 0, 0, 0 },
    { "ghosts/frightened/white_1", 1, 16, 16, 4, hd_p51, 1, hd_c51, 0, 0, 0, 0 },
    { "ghosts/frightened/blue_2", 1, 16, 16, 4, hd_p52, 1, hd_c52, 0, 0, 0, 0 },
    { "ghosts/frightened/white_2", 1, 16, 16, 4, hd_p53, 1, hd_c53, 0, 0, 0, 0 },
    { "ghosts/eyes/down", 1, 16, 16, 4, hd_p54, 2, hd_c54, 0, 0, 1, 0 },
    { "ghosts/eyes/right", 1, 16, 16, 4, hd_p55, 2, hd_c55, 0, 0, 1, 0 },
    { "ghosts/eyes/left", 1, 16, 16, 4, hd_p56, 2, hd_c56, "ghosts/eyes/right", 'h', 1, 0 },
    { "ghosts/eyes/up", 1, 16, 16, 4, hd_p57, 3, hd_c57, 0, 0, 1, 0 },
    { "fruit/cherry", 1, 16, 16, 4, hd_p58, 1, hd_c58, 0, 0, 1, 0 },
    { "fruit/strawberry", 1, 16, 16, 4, hd_p59, 1, hd_c59, 0, 0, 1, 0 },
    { "fruit/orange", 1, 16, 16, 4, hd_p60, 1, hd_c60, 0, 0, 1, 0 },
    { "fruit/apple", 1, 16, 16, 4, hd_p61, 1, hd_c61, 0, 0, 1, 0 },
    { "fruit/melon", 1, 16, 16, 4, hd_p62, 1, hd_c62, 0, 0, 1, 0 },
    { "fruit/galaxian", 1, 16, 16, 4, hd_p63, 1, hd_c63, 0, 0, 1, 0 },
    { "fruit/bell", 1, 16, 16, 4, hd_p64, 1, hd_c64, 0, 0, 1, 0 },
    { "fruit/key", 1, 16, 16, 4, hd_p65, 1, hd_c65, 0, 0, 1, 0 },
    { "scores/100", 1, 16, 16, 4, hd_p66, 1, hd_c66, 0, 0, 1, 0 },
    { "scores/200", 1, 16, 16, 4, hd_p67, 2, hd_c67, 0, 0, 1, 0 },
    { "scores/400", 1, 16, 16, 4, hd_p68, 2, hd_c68, 0, 0, 1, 0 },
    { "scores/800", 1, 16, 16, 4, hd_p69, 1, hd_c69, 0, 0, 1, 0 },
    { "scores/1600", 1, 16, 16, 4, hd_p70, 1, hd_c70, 0, 0, 1, 0 },
    { "hud/fruit_cherry", 0, 16, 16, 4, hd_p71, 0, 0, 0, 0, 1, 0 },
    { "hud/fruit_strawberry", 0, 16, 16, 4, hd_p72, 0, 0, 0, 0, 1, 0 },
    { "hud/fruit_orange", 0, 16, 16, 4, hd_p73, 0, 0, 0, 0, 1, 0 },
    { "hud/fruit_apple", 0, 16, 16, 4, hd_p74, 0, 0, 0, 0, 1, 0 },
    { "hud/fruit_melon", 0, 16, 16, 4, hd_p75, 0, 0, 0, 0, 1, 0 },
    { "hud/fruit_galaxian", 0, 16, 16, 4, hd_p76, 0, 0, 0, 0, 1, 0 },
    { "hud/fruit_bell", 0, 16, 16, 4, hd_p77, 0, 0, 0, 0, 1, 0 },
    { "hud/fruit_key", 0, 16, 16, 4, hd_p78, 0, 0, 0, 0, 1, 0 },
    { "hud/lives", 0, 16, 16, 4, hd_p79, 0, 0, 0, 0, 1, 0 },
    { "dot", 0, 8, 8, 1, hd_p80, 0, 0, 0, 0, 1, 0 },
    { "dot_alt", 0, 8, 8, 1, hd_p81, 0, 0, "dot", 'n', 1, 0 },
    { "power_pellet", 0, 8, 8, 1, hd_p82, 0, 0, 0, 0, 1, 0 },
    { "font/A", 0, 8, 8, 1, hd_p83, 4, hd_c83, 0, 0, 0, 1 },
    { "font/B", 0, 8, 8, 1, hd_p84, 4, hd_c84, 0, 0, 0, 1 },
    { "font/C", 0, 8, 8, 1, hd_p85, 4, hd_c85, 0, 0, 0, 1 },
    { "font/D", 0, 8, 8, 1, hd_p86, 4, hd_c86, 0, 0, 0, 1 },
    { "font/E", 0, 8, 8, 1, hd_p87, 4, hd_c87, 0, 0, 0, 1 },
    { "font/F", 0, 8, 8, 1, hd_p88, 4, hd_c88, 0, 0, 0, 1 },
    { "font/G", 0, 8, 8, 1, hd_p89, 4, hd_c89, 0, 0, 0, 1 },
    { "font/H", 0, 8, 8, 1, hd_p90, 4, hd_c90, 0, 0, 0, 1 },
    { "font/I", 0, 8, 8, 1, hd_p91, 4, hd_c91, 0, 0, 0, 1 },
    { "font/J", 0, 8, 8, 1, hd_p92, 4, hd_c92, 0, 0, 0, 1 },
    { "font/K", 0, 8, 8, 1, hd_p93, 4, hd_c93, 0, 0, 0, 1 },
    { "font/L", 0, 8, 8, 1, hd_p94, 4, hd_c94, 0, 0, 0, 1 },
    { "font/M", 0, 8, 8, 1, hd_p95, 4, hd_c95, 0, 0, 0, 1 },
    { "font/N", 0, 8, 8, 1, hd_p96, 4, hd_c96, 0, 0, 0, 1 },
    { "font/O", 0, 8, 8, 1, hd_p97, 4, hd_c97, 0, 0, 0, 1 },
    { "font/P", 0, 8, 8, 1, hd_p98, 4, hd_c98, 0, 0, 0, 1 },
    { "font/Q", 0, 8, 8, 1, hd_p99, 4, hd_c99, 0, 0, 0, 1 },
    { "font/R", 0, 8, 8, 1, hd_p100, 4, hd_c100, 0, 0, 0, 1 },
    { "font/S", 0, 8, 8, 1, hd_p101, 4, hd_c101, 0, 0, 0, 1 },
    { "font/T", 0, 8, 8, 1, hd_p102, 4, hd_c102, 0, 0, 0, 1 },
    { "font/U", 0, 8, 8, 1, hd_p103, 4, hd_c103, 0, 0, 0, 1 },
    { "font/V", 0, 8, 8, 1, hd_p104, 4, hd_c104, 0, 0, 0, 1 },
    { "font/W", 0, 8, 8, 1, hd_p105, 4, hd_c105, 0, 0, 0, 1 },
    { "font/X", 0, 8, 8, 1, hd_p106, 4, hd_c106, 0, 0, 0, 1 },
    { "font/Y", 0, 8, 8, 1, hd_p107, 4, hd_c107, 0, 0, 0, 1 },
    { "font/Z", 0, 8, 8, 1, hd_p108, 4, hd_c108, 0, 0, 0, 1 },
    { "font/0", 0, 8, 8, 1, hd_p109, 4, hd_c109, 0, 0, 0, 1 },
    { "font/1", 0, 8, 8, 1, hd_p110, 4, hd_c110, 0, 0, 0, 1 },
    { "font/2", 0, 8, 8, 1, hd_p111, 4, hd_c111, 0, 0, 0, 1 },
    { "font/3", 0, 8, 8, 1, hd_p112, 4, hd_c112, 0, 0, 0, 1 },
    { "font/4", 0, 8, 8, 1, hd_p113, 4, hd_c113, 0, 0, 0, 1 },
    { "font/5", 0, 8, 8, 1, hd_p114, 4, hd_c114, 0, 0, 0, 1 },
    { "font/6", 0, 8, 8, 1, hd_p115, 4, hd_c115, 0, 0, 0, 1 },
    { "font/7", 0, 8, 8, 1, hd_p116, 4, hd_c116, 0, 0, 0, 1 },
    { "font/8", 0, 8, 8, 1, hd_p117, 4, hd_c117, 0, 0, 0, 1 },
    { "font/9", 0, 8, 8, 1, hd_p118, 4, hd_c118, 0, 0, 0, 1 },
    { "font/dash", 0, 8, 8, 1, hd_p119, 4, hd_c119, 0, 0, 0, 1 },
    { "font/period", 0, 8, 8, 1, hd_p120, 4, hd_c120, 0, 0, 0, 1 },
    { "font/cursor", 0, 8, 8, 1, hd_p121, 4, hd_c121, 0, 0, 0, 1 },
    { "font/copyright", 0, 8, 8, 1, hd_p122, 4, hd_c122, 0, 0, 0, 1 },
};
#define HD_GRAPHICS_N ((int)(sizeof(hd_graphics) / sizeof(hd_graphics[0])))
